version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: imfa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imfa
      MYSQL_USER: imfa
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  redis:
    image: redis:7.2
    container_name: imfa-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 60 1000
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    restart: unless-stopped


volumes:
  mysql_data:
  redis_data:
